timestamp: '2025-02-02T13:26:42.812769'
joints:
  shoulder_pan:
    max:
      ticks: 3549
    center:
      ticks: 2048
    min:
      ticks: 831
      speed: 10
      load: 0
    meta:
      homing_offset: 1368
  shoulder_lift:
    min:
      ticks: 820
      speed: 0
      load: 0
    center:
      ticks: 2048
    max:
      ticks: 3247
    meta:
      homing_offset: 1023
  elbow_flex:
    min:
      ticks: 773
      speed: 0
      load: 0
    center:
      ticks: 2048
    max:
      ticks: 3080
    meta:
      homing_offset: -924
  wrist_flex:
    min:
      ticks: 948
    center:
      ticks: 2048
    max:
      ticks: 3283
    meta:
      homing_offset: -1018
  wrist_roll:
    min:
      ticks: 0
      speed: 0
    center:
      ticks: 2048
    max:
      ticks: 4095
    meta:
      homing_offset: 787
  gripper:
    min:
      ticks: 1200
      speed: 0
      load: 0
    center:
      ticks: 2048
      speed: -1
      load: 0
    max:
      ticks: 3299
      speed: 0
      load: 0
    meta:
      homing_offset: -942
